- name: variables from external file
  hosts: local
  connection: local
  vars_files:  
    - course.yaml         #importing variables from external file
  # vars:
  #   course: "ansible for beginners"     #playlevel variable
  #   duration: "2 hours"
  #   trainer: "Anusha"
  tasks:
  - name: print course details
    vars:
      course: "Terraform"             #task level variable and it will override play level variable
    ansible.builtin.debug:
      msg: "course: {{ course }}, duration: {{ duration }}, trainer: {{ trainer }}"
