- name: check number is less than 10 or not
  hosts: local
  connection: local
  vars:
    num: 5
  tasks:
   - name: print message if number is less than 10
     ansible.builtin.debug:
      msg: "number is less than 10"
     when: num < 10