- name: command vs shell
  hosts: local
  connection: local
  tasks:
    - name: checking shell module
      # ansible.builtin.command: cat /etc/passwd | grep root   #this command will not work as pipe is not supported in command module
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: users_output 

    - name: print users output
      ansible.builtin.debug:
        msg: "{{ users_output }}"