- name: demo on conditions
  hosts: local
  connection: local
  vars:
      is_valid: true
    # is_valid: false     #skipping the task as the condition is false
  tasks:
  - name: print valid message
    ansible.builtin.debug:
      msg: "This is valid"
    when: is_valid