- name: demo on error handling
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id roboshop
    register: result
    ignore_errors: yes   #it will ignore the error and continue with next task

  - name: print results
    ansible.builtin.debug:
      msg: "{{ result }}"

  - name: create user
    ansible.builtin.command: useradd roboshop
    when: result.rc != 0   #it will create user only if the user does not exist, as the command will return non zero exit code if user does not exist
          