- name: demo on conditions/filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform, devops
    course: "ansible for beginners"
    ip: "256.654.845.11"  #invalid IP address
    tags:                            #dictionary variable
      name: ansible
      project: roboshop
      component: catalogue  
  tasks:
   - name: greetings
     ansible.builtin.debug:
      msg: "Hello {{ name | default('Guest') }}"  #using default filter to provide a default value if the variable is not defined


   - name: print topics as list
     ansible.builtin.debug:
       msg: "Topics: {{ topics | split(', ') }}"   #using split filter to convert string into list based on the separator provided

   - name: convert map to list
     ansible.builtin.debug:
       msg: "Tags: {{ tags | dict2items }}"   #using dict2items filter to convert dictionary into list of dictionaries with key and value as keys 
  
   - name: convert to upper
     ansible.builtin.debug:
       msg: "Course: {{ course | upper }}"   #using upper filter to convert string to uppercase

   - name: convert to lower
     ansible.builtin.debug:
       msg: "Course: {{ course | lower }}"   #using lower filter to convert string to lowercase
   - name: check if ip is valid
     ansible.builtin.debug:
       msg: "IP: {{ ip | ansible.utils.ipv4}}"   #pip3.9 install netaddr
       #using ipaddr filter to check if the IP address is valid