- name: demo on conditions/filters
  hosts: local
  connection: local
  tasks:
   - name: greetings
      ansible.builtin.debug:
        msg: "Hello {{ name | default('Guest') }}"  #using default filter to provide a default value if the variable is not defined