- name: demo on conditions/filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform, devops
  tags:
    name: ansible
    project: roboshop
    component: catalogue  
  tasks:
   - name: greetings
     ansible.builtin.debug:
      msg: "Hello {{ name | default('Guest') }}"  #using default filter to provide a default value if the variable is not defined


   - name: print topics as list
     ansible.builtin.debug:
       msg: "Topics: {{ topics | split(', ') }}"   #using split filter to convert string into list based on the separator provided

   - name: convert map to list
     ansible.builtin.debug:
       msg: "Tags: {{ tags | dict2items }}"   #using dict2items filter to convert dictionary into list of dictionaries with key and value as keys 