- name: install packages
  hosts: local
  connection: local
  bacome: yes
  tasks:
  - name: installing packages using loop
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - zip